output a proper error message if the bug does not exist
Otherwise one would see the following misleading message:

    File "/usr/lib/python-exec/python3.8/tatt", line 155, in <module>
      response = response["bugs"][0]
  IndexError: list index out of range

Signed-off-by: Rolf Eike Beer <eike@sf-mail.de>